import type { Metadata } from "next";
import { Navbar } from "@/components";

import './globals.css'
import  SessionProvider from "../utils/sessionProvider";
import { getServerSession } from "next-auth";
import StoreHelper from "@/utils/storeHelper";
import { useStore } from "zustand";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)



{
  const session = await getServerSession()
  return (
    <html lang="en">
      <body >
        <SessionProvider session={session}>
        <Navbar/>
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
